# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

# Server
source:           source/site
destination:      .publish
host:             localhost
port:             9002
baseurl:          /
encoding:         UTF-8

gems:
  - jekyll-sitemap
