# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

# Server
source:           source/site
destination:      _gh_pages
host:             localhost
port:             9005
baseurl:          /
encoding:         UTF-8

gems:
  - jekyll-sitemap
